package org.wikidata.wdtk.datamodel.json.jackson.datavalues;

/*
 * #%L
 * Wikidata Toolkit Data Model
 * %%
 * Copyright (C) 2014 Wikidata Toolkit Developers
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class JacksonInnerQuantity {

	private BigDecimal amount;
	private BigDecimal upperBound;
	private BigDecimal lowerBound;

	public JacksonInnerQuantity() {
	}

	public JacksonInnerQuantity(BigDecimal amount, BigDecimal upperBound,
			BigDecimal lowerBound) {
		this.amount = amount;
		this.upperBound = upperBound;
		this.lowerBound = lowerBound;
	}

	/**
	 * Formats the String output with a leading signum as JSON expects it.
	 * 
	 * @param value
	 * @return
	 */
	private String withSignum(BigDecimal value) {
		if (value.signum() < 0) {
			return value.toString();
		}
		return "+" + value.toString();
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getUpperBound() {
		return upperBound;
	}

	public void setUpperBound(BigDecimal upperBound) {
		this.upperBound = upperBound;
	}

	public BigDecimal getLowerBound() {
		return lowerBound;
	}

	public void setLowerBound(BigDecimal lowerBound) {
		this.lowerBound = lowerBound;
	}

	@JsonProperty("amount")
	public String getAmountAsString() {
		return this.withSignum(this.amount);
	}

	@JsonProperty("upperBound")
	public String getUpperBoundAsString() {
		return this.withSignum(this.upperBound);
	}

	@JsonProperty("lowerBound")
	public String getLowerBoundAsString() {
		return this.withSignum(this.lowerBound);
	}

	/**
	 * In JSON, the Quantities include the "unit"-field. It seems to have no use
	 * and is written out as the value 1 just to be compatible with the JSON
	 * generated by other sources.
	 * 
	 * @return
	 */
	@JsonProperty("unit")
	public String getUnit() {
		return "1";
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof JacksonInnerQuantity)) {
			return false;
		}
		JacksonInnerQuantity other = (JacksonInnerQuantity) o;

		return this.amount.equals(other.amount)
				&& this.lowerBound.equals(other.lowerBound)
				&& this.upperBound.equals(other.upperBound);

	}

}
