package org.wikidata.wdtk.datamodel.json.jackson.datavalues;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Quantity {

	private BigDecimal amount;
	private BigDecimal upperBound;
	private BigDecimal lowerBound;

	public Quantity() {
	}

	public Quantity(BigDecimal amount, BigDecimal upperBound,
			BigDecimal lowerBound) {
		this.amount = amount;
		this.upperBound = upperBound;
		this.lowerBound = lowerBound;
	}

	/**
	 * Formats the String output with a leading signum as JSON expects it.
	 * 
	 * @param value
	 * @return
	 */
	private String withSignum(BigDecimal value) {
		if (value.signum() < 0) {
			return value.toString();
		}
		return "+" + value.toString();
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getUpperBound() {
		return upperBound;
	}

	public void setUpperBound(BigDecimal upperBound) {
		this.upperBound = upperBound;
	}

	public BigDecimal getLowerBound() {
		return lowerBound;
	}

	public void setLowerBound(BigDecimal lowerBound) {
		this.lowerBound = lowerBound;
	}

	@JsonProperty("amount")
	public String getAmountAsString() {
		return this.withSignum(this.amount);
	}

	@JsonProperty("upperBound")
	public String getUpperBoundAsString() {
		return this.withSignum(this.upperBound);
	}

	@JsonProperty("lowerBound")
	public String getLowerBoundAsString() {
		return this.withSignum(this.lowerBound);
	}

	/**
	 * In JSON, the Quantities include the "unit"-field. It seems to have no use
	 * and is written out as the value 1 just to be compatible with the JSON
	 * generated by other sources.
	 * 
	 * @return
	 */
	@JsonProperty("unit")
	public String getUnit() {
		return "1";
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof Quantity)) {
			return false;
		}
		Quantity other = (Quantity) o;

		return this.amount.equals(other.amount)
				&& this.lowerBound.equals(other.lowerBound)
				&& this.upperBound.equals(other.upperBound);

	}

}
