package org.wikidata.wdtk.client;

/*
 * #%L
 * Wikidata Toolkit Command-line Tool
 * %%
 * Copyright (C) 2014 - 2015 Wikidata Toolkit Developers
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * This class represent a report which contains messages which gives you
 * information which kind of outputs were generated by a
 * {@link DumpProcessingAction}. It gives you the possiblity to print these
 * messages into a file.
 * 
 * @author Michael Günther
 * 
 */
public class Report {
	final List<String> entries = new ArrayList<String>();

	String reportFilename;

	boolean printReport = false;

	public void setReportFile(String reportFilename) {
		this.reportFilename = reportFilename;
		this.printReport = true;
	}

	public void addEntry(String entry) {
		entries.add(entry);
	}

	public String createReport() {
		StringBuilder builder = new StringBuilder();
		for (String entry : entries) {
			builder.append(entry);
			builder.append(System.getProperty("line.separator"));
		}

		return builder.toString();
	}

	public void printReport() throws IOException {
		if (printReport) {
			File reportFile = new File(this.reportFilename);
			BufferedWriter writer = new BufferedWriter(new FileWriter(
					reportFile));
			writer.write(this.createReport());
			writer.close();
		}
	}
}
